### PR TITLE
Fixed a few typos

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Review by Song921012 — APPROVED** [review]

**Comment by Song921012** [comment]
Thank you, Pitmonticone.

**Comment by pitmonticone** [comment]
Thank you @Song921012, great resource aggregation effort!

**Comment by Song921012** [comment]
I am wondering if you can invite me to JuliaEpi. If it is not suitable for you, just ignore my message. My email is aidishage@gmail.com.@pitmonticone

**Comment by pitmonticone** [comment]
Glad to hear you're interested @Song921012, I would be happy to invite you! 

Would you like to [transfer](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) some Mathepia or some other JuliaEpi-relevant repo(s) over there? 

Obviously you would continue to maintain full permissions to the repo.

**Comment by Song921012** [comment]
Sure.

**Comment by pitmonticone** [comment]
Ok then. I've activated the option that allows members to [transfer](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) the JuliaEpi-relevant repos. It should be quick and all the links will be redirected so that you don't need to change anything manually.

**Comment by pitmonticone** [comment]
Just invited you @Song921012.

I believe that [MathEpiDeepLearning](https://github.com/Song921012/MathEpiDeepLearning), [MathEpiDeepLearningTutorial](https://github.com/Song921012/MathEpiDeepLearningTutorial) and all the [Mathepia](https://github.com/Mathepia) repos could be well suited for JuliaEpi.

Please let me know when you finish the migration of the repos so that I can check everything is ok and formally end the procedure.

**Pull request merged**
